// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: suffixarray.proto

public final class SuffixArrayProto {
  private SuffixArrayProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SuffixMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SuffixMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string genome = 1;</code>
     */
    java.lang.String getGenome();
    /**
     * <code>string genome = 1;</code>
     */
    com.google.protobuf.ByteString
        getGenomeBytes();

    /**
     * <code>repeated int32 suffixArray = 2;</code>
     */
    java.util.List<java.lang.Integer> getSuffixArrayList();
    /**
     * <code>repeated int32 suffixArray = 2;</code>
     */
    int getSuffixArrayCount();
    /**
     * <code>repeated int32 suffixArray = 2;</code>
     */
    int getSuffixArray(int index);

    /**
     * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
     */
    int getPreftabCount();
    /**
     * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
     */
    boolean containsPreftab(
        java.lang.String key);
    /**
     * Use {@link #getPreftabMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, SuffixArrayProto.indexInterval>
    getPreftab();
    /**
     * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
     */
    java.util.Map<java.lang.String, SuffixArrayProto.indexInterval>
    getPreftabMap();
    /**
     * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
     */

    SuffixArrayProto.indexInterval getPreftabOrDefault(
        java.lang.String key,
        SuffixArrayProto.indexInterval defaultValue);
    /**
     * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
     */

    SuffixArrayProto.indexInterval getPreftabOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code SuffixMessage}
   */
  public  static final class SuffixMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SuffixMessage)
      SuffixMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SuffixMessage.newBuilder() to construct.
    private SuffixMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SuffixMessage() {
      genome_ = "";
      suffixArray_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SuffixMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              genome_ = s;
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                suffixArray_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              suffixArray_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                suffixArray_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                suffixArray_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                preftab_ = com.google.protobuf.MapField.newMapField(
                    PreftabDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, SuffixArrayProto.indexInterval>
              preftab__ = input.readMessage(
                  PreftabDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              preftab_.getMutableMap().put(
                  preftab__.getKey(), preftab__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          suffixArray_ = java.util.Collections.unmodifiableList(suffixArray_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SuffixArrayProto.internal_static_SuffixMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetPreftab();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SuffixArrayProto.internal_static_SuffixMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SuffixArrayProto.SuffixMessage.class, SuffixArrayProto.SuffixMessage.Builder.class);
    }

    private int bitField0_;
    public static final int GENOME_FIELD_NUMBER = 1;
    private volatile java.lang.Object genome_;
    /**
     * <code>string genome = 1;</code>
     */
    public java.lang.String getGenome() {
      java.lang.Object ref = genome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genome_ = s;
        return s;
      }
    }
    /**
     * <code>string genome = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGenomeBytes() {
      java.lang.Object ref = genome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUFFIXARRAY_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> suffixArray_;
    /**
     * <code>repeated int32 suffixArray = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getSuffixArrayList() {
      return suffixArray_;
    }
    /**
     * <code>repeated int32 suffixArray = 2;</code>
     */
    public int getSuffixArrayCount() {
      return suffixArray_.size();
    }
    /**
     * <code>repeated int32 suffixArray = 2;</code>
     */
    public int getSuffixArray(int index) {
      return suffixArray_.get(index);
    }
    private int suffixArrayMemoizedSerializedSize = -1;

    public static final int PREFTAB_FIELD_NUMBER = 3;
    private static final class PreftabDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, SuffixArrayProto.indexInterval> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, SuffixArrayProto.indexInterval>newDefaultInstance(
                  SuffixArrayProto.internal_static_SuffixMessage_PreftabEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  SuffixArrayProto.indexInterval.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, SuffixArrayProto.indexInterval> preftab_;
    private com.google.protobuf.MapField<java.lang.String, SuffixArrayProto.indexInterval>
    internalGetPreftab() {
      if (preftab_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PreftabDefaultEntryHolder.defaultEntry);
      }
      return preftab_;
    }

    public int getPreftabCount() {
      return internalGetPreftab().getMap().size();
    }
    /**
     * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
     */

    public boolean containsPreftab(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetPreftab().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPreftabMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, SuffixArrayProto.indexInterval> getPreftab() {
      return getPreftabMap();
    }
    /**
     * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
     */

    public java.util.Map<java.lang.String, SuffixArrayProto.indexInterval> getPreftabMap() {
      return internalGetPreftab().getMap();
    }
    /**
     * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
     */

    public SuffixArrayProto.indexInterval getPreftabOrDefault(
        java.lang.String key,
        SuffixArrayProto.indexInterval defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, SuffixArrayProto.indexInterval> map =
          internalGetPreftab().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
     */

    public SuffixArrayProto.indexInterval getPreftabOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, SuffixArrayProto.indexInterval> map =
          internalGetPreftab().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getGenomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, genome_);
      }
      if (getSuffixArrayList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(suffixArrayMemoizedSerializedSize);
      }
      for (int i = 0; i < suffixArray_.size(); i++) {
        output.writeInt32NoTag(suffixArray_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetPreftab(),
          PreftabDefaultEntryHolder.defaultEntry,
          3);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGenomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, genome_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < suffixArray_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(suffixArray_.get(i));
        }
        size += dataSize;
        if (!getSuffixArrayList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        suffixArrayMemoizedSerializedSize = dataSize;
      }
      for (java.util.Map.Entry<java.lang.String, SuffixArrayProto.indexInterval> entry
           : internalGetPreftab().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, SuffixArrayProto.indexInterval>
        preftab__ = PreftabDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, preftab__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SuffixArrayProto.SuffixMessage)) {
        return super.equals(obj);
      }
      SuffixArrayProto.SuffixMessage other = (SuffixArrayProto.SuffixMessage) obj;

      boolean result = true;
      result = result && getGenome()
          .equals(other.getGenome());
      result = result && getSuffixArrayList()
          .equals(other.getSuffixArrayList());
      result = result && internalGetPreftab().equals(
          other.internalGetPreftab());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GENOME_FIELD_NUMBER;
      hash = (53 * hash) + getGenome().hashCode();
      if (getSuffixArrayCount() > 0) {
        hash = (37 * hash) + SUFFIXARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getSuffixArrayList().hashCode();
      }
      if (!internalGetPreftab().getMap().isEmpty()) {
        hash = (37 * hash) + PREFTAB_FIELD_NUMBER;
        hash = (53 * hash) + internalGetPreftab().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SuffixArrayProto.SuffixMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SuffixArrayProto.SuffixMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SuffixArrayProto.SuffixMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SuffixArrayProto.SuffixMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SuffixArrayProto.SuffixMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SuffixArrayProto.SuffixMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SuffixArrayProto.SuffixMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SuffixArrayProto.SuffixMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SuffixArrayProto.SuffixMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SuffixArrayProto.SuffixMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SuffixArrayProto.SuffixMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SuffixArrayProto.SuffixMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SuffixArrayProto.SuffixMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SuffixMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SuffixMessage)
        SuffixArrayProto.SuffixMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SuffixArrayProto.internal_static_SuffixMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetPreftab();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutablePreftab();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SuffixArrayProto.internal_static_SuffixMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SuffixArrayProto.SuffixMessage.class, SuffixArrayProto.SuffixMessage.Builder.class);
      }

      // Construct using SuffixArrayProto.SuffixMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        genome_ = "";

        suffixArray_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutablePreftab().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SuffixArrayProto.internal_static_SuffixMessage_descriptor;
      }

      @java.lang.Override
      public SuffixArrayProto.SuffixMessage getDefaultInstanceForType() {
        return SuffixArrayProto.SuffixMessage.getDefaultInstance();
      }

      @java.lang.Override
      public SuffixArrayProto.SuffixMessage build() {
        SuffixArrayProto.SuffixMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SuffixArrayProto.SuffixMessage buildPartial() {
        SuffixArrayProto.SuffixMessage result = new SuffixArrayProto.SuffixMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.genome_ = genome_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          suffixArray_ = java.util.Collections.unmodifiableList(suffixArray_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.suffixArray_ = suffixArray_;
        result.preftab_ = internalGetPreftab();
        result.preftab_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SuffixArrayProto.SuffixMessage) {
          return mergeFrom((SuffixArrayProto.SuffixMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SuffixArrayProto.SuffixMessage other) {
        if (other == SuffixArrayProto.SuffixMessage.getDefaultInstance()) return this;
        if (!other.getGenome().isEmpty()) {
          genome_ = other.genome_;
          onChanged();
        }
        if (!other.suffixArray_.isEmpty()) {
          if (suffixArray_.isEmpty()) {
            suffixArray_ = other.suffixArray_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSuffixArrayIsMutable();
            suffixArray_.addAll(other.suffixArray_);
          }
          onChanged();
        }
        internalGetMutablePreftab().mergeFrom(
            other.internalGetPreftab());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SuffixArrayProto.SuffixMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SuffixArrayProto.SuffixMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object genome_ = "";
      /**
       * <code>string genome = 1;</code>
       */
      public java.lang.String getGenome() {
        java.lang.Object ref = genome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          genome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string genome = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGenomeBytes() {
        java.lang.Object ref = genome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          genome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string genome = 1;</code>
       */
      public Builder setGenome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        genome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string genome = 1;</code>
       */
      public Builder clearGenome() {
        
        genome_ = getDefaultInstance().getGenome();
        onChanged();
        return this;
      }
      /**
       * <code>string genome = 1;</code>
       */
      public Builder setGenomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        genome_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> suffixArray_ = java.util.Collections.emptyList();
      private void ensureSuffixArrayIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          suffixArray_ = new java.util.ArrayList<java.lang.Integer>(suffixArray_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 suffixArray = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getSuffixArrayList() {
        return java.util.Collections.unmodifiableList(suffixArray_);
      }
      /**
       * <code>repeated int32 suffixArray = 2;</code>
       */
      public int getSuffixArrayCount() {
        return suffixArray_.size();
      }
      /**
       * <code>repeated int32 suffixArray = 2;</code>
       */
      public int getSuffixArray(int index) {
        return suffixArray_.get(index);
      }
      /**
       * <code>repeated int32 suffixArray = 2;</code>
       */
      public Builder setSuffixArray(
          int index, int value) {
        ensureSuffixArrayIsMutable();
        suffixArray_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 suffixArray = 2;</code>
       */
      public Builder addSuffixArray(int value) {
        ensureSuffixArrayIsMutable();
        suffixArray_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 suffixArray = 2;</code>
       */
      public Builder addAllSuffixArray(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSuffixArrayIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, suffixArray_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 suffixArray = 2;</code>
       */
      public Builder clearSuffixArray() {
        suffixArray_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, SuffixArrayProto.indexInterval> preftab_;
      private com.google.protobuf.MapField<java.lang.String, SuffixArrayProto.indexInterval>
      internalGetPreftab() {
        if (preftab_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PreftabDefaultEntryHolder.defaultEntry);
        }
        return preftab_;
      }
      private com.google.protobuf.MapField<java.lang.String, SuffixArrayProto.indexInterval>
      internalGetMutablePreftab() {
        onChanged();;
        if (preftab_ == null) {
          preftab_ = com.google.protobuf.MapField.newMapField(
              PreftabDefaultEntryHolder.defaultEntry);
        }
        if (!preftab_.isMutable()) {
          preftab_ = preftab_.copy();
        }
        return preftab_;
      }

      public int getPreftabCount() {
        return internalGetPreftab().getMap().size();
      }
      /**
       * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
       */

      public boolean containsPreftab(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetPreftab().getMap().containsKey(key);
      }
      /**
       * Use {@link #getPreftabMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, SuffixArrayProto.indexInterval> getPreftab() {
        return getPreftabMap();
      }
      /**
       * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
       */

      public java.util.Map<java.lang.String, SuffixArrayProto.indexInterval> getPreftabMap() {
        return internalGetPreftab().getMap();
      }
      /**
       * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
       */

      public SuffixArrayProto.indexInterval getPreftabOrDefault(
          java.lang.String key,
          SuffixArrayProto.indexInterval defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, SuffixArrayProto.indexInterval> map =
            internalGetPreftab().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
       */

      public SuffixArrayProto.indexInterval getPreftabOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, SuffixArrayProto.indexInterval> map =
            internalGetPreftab().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearPreftab() {
        internalGetMutablePreftab().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
       */

      public Builder removePreftab(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutablePreftab().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, SuffixArrayProto.indexInterval>
      getMutablePreftab() {
        return internalGetMutablePreftab().getMutableMap();
      }
      /**
       * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
       */
      public Builder putPreftab(
          java.lang.String key,
          SuffixArrayProto.indexInterval value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutablePreftab().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .indexInterval&gt; preftab = 3;</code>
       */

      public Builder putAllPreftab(
          java.util.Map<java.lang.String, SuffixArrayProto.indexInterval> values) {
        internalGetMutablePreftab().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SuffixMessage)
    }

    // @@protoc_insertion_point(class_scope:SuffixMessage)
    private static final SuffixArrayProto.SuffixMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SuffixArrayProto.SuffixMessage();
    }

    public static SuffixArrayProto.SuffixMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SuffixMessage>
        PARSER = new com.google.protobuf.AbstractParser<SuffixMessage>() {
      @java.lang.Override
      public SuffixMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SuffixMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SuffixMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SuffixMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SuffixArrayProto.SuffixMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface indexIntervalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:indexInterval)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 indices = 4;</code>
     */
    java.util.List<java.lang.Integer> getIndicesList();
    /**
     * <code>repeated int32 indices = 4;</code>
     */
    int getIndicesCount();
    /**
     * <code>repeated int32 indices = 4;</code>
     */
    int getIndices(int index);
  }
  /**
   * Protobuf type {@code indexInterval}
   */
  public  static final class indexInterval extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:indexInterval)
      indexIntervalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use indexInterval.newBuilder() to construct.
    private indexInterval(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private indexInterval() {
      indices_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private indexInterval(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 32: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                indices_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              indices_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                indices_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                indices_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          indices_ = java.util.Collections.unmodifiableList(indices_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SuffixArrayProto.internal_static_indexInterval_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SuffixArrayProto.internal_static_indexInterval_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SuffixArrayProto.indexInterval.class, SuffixArrayProto.indexInterval.Builder.class);
    }

    public static final int INDICES_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> indices_;
    /**
     * <code>repeated int32 indices = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getIndicesList() {
      return indices_;
    }
    /**
     * <code>repeated int32 indices = 4;</code>
     */
    public int getIndicesCount() {
      return indices_.size();
    }
    /**
     * <code>repeated int32 indices = 4;</code>
     */
    public int getIndices(int index) {
      return indices_.get(index);
    }
    private int indicesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getIndicesList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(indicesMemoizedSerializedSize);
      }
      for (int i = 0; i < indices_.size(); i++) {
        output.writeInt32NoTag(indices_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < indices_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(indices_.get(i));
        }
        size += dataSize;
        if (!getIndicesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        indicesMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SuffixArrayProto.indexInterval)) {
        return super.equals(obj);
      }
      SuffixArrayProto.indexInterval other = (SuffixArrayProto.indexInterval) obj;

      boolean result = true;
      result = result && getIndicesList()
          .equals(other.getIndicesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIndicesCount() > 0) {
        hash = (37 * hash) + INDICES_FIELD_NUMBER;
        hash = (53 * hash) + getIndicesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SuffixArrayProto.indexInterval parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SuffixArrayProto.indexInterval parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SuffixArrayProto.indexInterval parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SuffixArrayProto.indexInterval parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SuffixArrayProto.indexInterval parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SuffixArrayProto.indexInterval parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SuffixArrayProto.indexInterval parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SuffixArrayProto.indexInterval parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SuffixArrayProto.indexInterval parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SuffixArrayProto.indexInterval parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SuffixArrayProto.indexInterval parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SuffixArrayProto.indexInterval parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SuffixArrayProto.indexInterval prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code indexInterval}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:indexInterval)
        SuffixArrayProto.indexIntervalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SuffixArrayProto.internal_static_indexInterval_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SuffixArrayProto.internal_static_indexInterval_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SuffixArrayProto.indexInterval.class, SuffixArrayProto.indexInterval.Builder.class);
      }

      // Construct using SuffixArrayProto.indexInterval.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        indices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SuffixArrayProto.internal_static_indexInterval_descriptor;
      }

      @java.lang.Override
      public SuffixArrayProto.indexInterval getDefaultInstanceForType() {
        return SuffixArrayProto.indexInterval.getDefaultInstance();
      }

      @java.lang.Override
      public SuffixArrayProto.indexInterval build() {
        SuffixArrayProto.indexInterval result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SuffixArrayProto.indexInterval buildPartial() {
        SuffixArrayProto.indexInterval result = new SuffixArrayProto.indexInterval(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          indices_ = java.util.Collections.unmodifiableList(indices_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.indices_ = indices_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SuffixArrayProto.indexInterval) {
          return mergeFrom((SuffixArrayProto.indexInterval)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SuffixArrayProto.indexInterval other) {
        if (other == SuffixArrayProto.indexInterval.getDefaultInstance()) return this;
        if (!other.indices_.isEmpty()) {
          if (indices_.isEmpty()) {
            indices_ = other.indices_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIndicesIsMutable();
            indices_.addAll(other.indices_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SuffixArrayProto.indexInterval parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SuffixArrayProto.indexInterval) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> indices_ = java.util.Collections.emptyList();
      private void ensureIndicesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          indices_ = new java.util.ArrayList<java.lang.Integer>(indices_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 indices = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getIndicesList() {
        return java.util.Collections.unmodifiableList(indices_);
      }
      /**
       * <code>repeated int32 indices = 4;</code>
       */
      public int getIndicesCount() {
        return indices_.size();
      }
      /**
       * <code>repeated int32 indices = 4;</code>
       */
      public int getIndices(int index) {
        return indices_.get(index);
      }
      /**
       * <code>repeated int32 indices = 4;</code>
       */
      public Builder setIndices(
          int index, int value) {
        ensureIndicesIsMutable();
        indices_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 indices = 4;</code>
       */
      public Builder addIndices(int value) {
        ensureIndicesIsMutable();
        indices_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 indices = 4;</code>
       */
      public Builder addAllIndices(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIndicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, indices_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 indices = 4;</code>
       */
      public Builder clearIndices() {
        indices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:indexInterval)
    }

    // @@protoc_insertion_point(class_scope:indexInterval)
    private static final SuffixArrayProto.indexInterval DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SuffixArrayProto.indexInterval();
    }

    public static SuffixArrayProto.indexInterval getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<indexInterval>
        PARSER = new com.google.protobuf.AbstractParser<indexInterval>() {
      @java.lang.Override
      public indexInterval parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new indexInterval(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<indexInterval> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<indexInterval> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SuffixArrayProto.indexInterval getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SuffixMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SuffixMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SuffixMessage_PreftabEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SuffixMessage_PreftabEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_indexInterval_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_indexInterval_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021suffixarray.proto\"\242\001\n\rSuffixMessage\022\016\n" +
      "\006genome\030\001 \001(\t\022\023\n\013suffixArray\030\002 \003(\005\022,\n\007pr" +
      "eftab\030\003 \003(\0132\033.SuffixMessage.PreftabEntry" +
      "\032>\n\014PreftabEntry\022\013\n\003key\030\001 \001(\t\022\035\n\005value\030\002" +
      " \001(\0132\016.indexInterval:\0028\001\" \n\rindexInterva" +
      "l\022\017\n\007indices\030\004 \003(\005B\022B\020SuffixArrayProtob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SuffixMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SuffixMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SuffixMessage_descriptor,
        new java.lang.String[] { "Genome", "SuffixArray", "Preftab", });
    internal_static_SuffixMessage_PreftabEntry_descriptor =
      internal_static_SuffixMessage_descriptor.getNestedTypes().get(0);
    internal_static_SuffixMessage_PreftabEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SuffixMessage_PreftabEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_indexInterval_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_indexInterval_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_indexInterval_descriptor,
        new java.lang.String[] { "Indices", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
